name: rworkflows_dev
'on':
  push:
    branches:
    - master
    - main
    - devel
    - RELEASE_**
    - dev
  pull_request:
    branches:
    - master
    - main
    - devel
    - RELEASE_**
    - dev
jobs:
  rworkflows:
    permissions: write-all
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    container: ${{ matrix.config.cont }}
    strategy:
      fail-fast: ${{ false }}
      matrix:
        config:
        - os: ubuntu-latest
          r: devel
          bioc: devel
          cont: ghcr.io/bioconductor/bioconductor_docker:devel
          rspm: https://packagemanager.rstudio.com/cran/__linux__/latest/release
        - os: macOS-latest
          r: latest
          bioc: release
        - os: windows-latest
          r: latest
          bioc: release
    steps:
    - uses: neurogenomics/rworkflows@dev
      with:
        run_bioccheck: ${{ false }}
        run_rcmdcheck: ${{ false }}
        as_cran: ${{ true }}
        run_vignettes: ${{ false }}
        has_testthat: ${{ false }}
        run_covr: ${{ false }}
        run_pkgdown: ${{ false }}
        has_runit: ${{ false }}
        has_latex: ${{ false }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run_docker: ${{ true }}
        docker_user: bschilder
        docker_org: neurogenomicslab
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        runner_os: ${{ runner.os }}
        cache_version: cache-v1
